finchcollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls'))
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('finches/', views.finches_index, name='index'),
    path('finches/<int:finch_id>/', views.finches_detail, name='detail'),
    path('finches/create/', views.FinchCreate.as_view(), name='finch_create'),
    path('finches/<int:pk>/update/',
         views.FinchUpdate.as_view(), name='finch_update'),
    path('finches/<int:pk>/delete/',
         views.FinchDelete.as_view(), name='finch_delete'),
    path('finches/<int:finch_id>/add_napping/',
         views.add_napping, name='add_napping'),
    path('finches/<int:finch_id>/assoc_seed/<int:seed_id>/',
         views.assoc_seed, name='assoc_seed'),
    path('seeds/', views.SeedList.as_view(), name='seeds_index'),
    path('seeds/<int:pk>/', views.SeedDetail.as_view(), name='seeds_detail'),
    path('seeds/create/', views.SeedCreate.as_view(), name='seeds_create'),
    path('seeds/<int:pk>/update/', views.SeedUpdate.as_view(), name='seeds_update'),
    path('seeds/<int:pk>/delete/', views.SeedDelete.as_view(), name='seeds_delete'),
]

main_app/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
NAP = (
    ('M', 'Morning'),
    ('A', 'Afternoon'),
    ('E', 'Evening')
)


class Seed(models.Model):
    name = models.CharField(max_length=50)
    color = models.CharField(max_length=20)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('seeds_detail', kwargs={'pk': self.id})


class Finch(models.Model):
    name = models.CharField(max_length=100)
    size = models.CharField(max_length=100)
    color = models.CharField(max_length=100)
    behavior = models.TextField(max_length=150)
    seeds = models.ManyToManyField(Seed)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('detail', kwargs={'finch_id': self.id})


class Napping(models.Model):
    date = models.DateField('nap date')
    nap = models.CharField(
        max_length=1,
        choices=NAP,
        default=NAP[0][0]
    )
    finch = models.ForeignKey(Finch, on_delete=models.CASCADE)

    def __str__(self):
        # get_<field>_display grabs the choice
        return f"{self.get_nap_display()} on {self.date}"

    class Meta:
        ordering = ['-date']

main_app/forms.py
from django.forms import ModelForm
from .models import *


class NappingForm(ModelForm):
    class Meta:
        model = Napping
        fields = ['date', 'nap']

main_app/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import *
from .forms import NappingForm
from django.views.generic import CreateView, UpdateView, DeleteView, ListView, DetailView
# Create your views here.


def home(request):
    return HttpResponse('this is home')


def about(request):
    return render(request, 'about.html')


def finches_index(request):
    finches = Finch.objects.all()
    return render(request, 'finches/index.html', {'finches': finches})


def finches_detail(request, finch_id):
    finch = Finch.objects.get(id=finch_id)
    seeds_finch_doesnt_have = Seed.objects.exclude(
        id__in=finch.seeds.all().values_list('id')
    )
    napping_form = NappingForm()
    return render(request, 'finches/detail.html', {
        'finch': finch,
        'napping_form': napping_form,
        'seeds': seeds_finch_doesnt_have
    })


def add_napping(request, finch_id):
    form = NappingForm(request.POST)
    if form.is_valid():
        new_napping = form.save(commit=False)
        new_napping.finch_id = finch_id
        new_napping.save()
    return redirect('detail', finch_id=finch_id)


class SeedList(ListView):
    model = Seed


class SeedDetail(DetailView):
    model = Seed


class SeedCreate(CreateView):
    model = Seed
    fields = '__all__'


class SeedUpdate(UpdateView):
    model = Seed
    fields = ['name']


class SeedDelete(DeleteView):
    model = Seed
    success_url = '/seeds/'


class FinchCreate(CreateView):
    model = Finch
    fields = ['name', 'size', 'color', 'behavior']


class FinchUpdate(UpdateView):
    model = Finch
    fields = ['size', 'color', 'behavior']


class FinchDelete(DeleteView):
    model = Finch
    success_url = '/finches/'


def assoc_seed(request, finch_id, seed_id):
    Finch.objects.get(id=finch_id).seeds.add(seed_id)
    return redirect('detail', finch_id=finch_id)

main_app/templates/about.html
{% extends 'base.html'%} {% block content %}

<h1>This is the about page</h1>

{% endblock %}

main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Finch Collector</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
  </head>
  <body>
    <header class="navbar-fixed">
      <nav>
        <div class="nav-wrapper">
          <ul>
            <li>
              <a href="/finches" class="left brand-logo">&nbsp;&nbsp;FinchCollector</a>
            </li>
          </ul>
          <ul class="right">
            <li><a href="/about">About</a></li>
            <!-- new markup below -->
            <li><a href="{% url 'finch_create' %}">Add a Finch</a></li>
            <li><a href="{% url 'index' %}">View finches</a></li>
            <li><a href="{% url 'seeds_create' %}">Add Seed</a></li>
            <li><a href="{% url 'seeds_index' %}">View Seeds</a></li>
            <li><a href="{% url 'index' %}">View finches</a></li>
          </ul>
        </div>
      </nav>
    </header>
    <main class="container">{% block content %} {% endblock %}</main>
    <footer class="page-footer">
      <div class="right">&copy; Finches &nbsp;</div>
    </footer>
  </body>
</html>

main_app/templates/finches/detail.html
{% extends 'base.html' %} 
{% block content %}

<h1>Finch List</h1>

<div class="row">
  <div class="col s6">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ finch.name }}</span>
        <p>Size: {{ finch.size }}cm</p>
        <p>Color: {{ finch.color }}</p>
        <p>Behavior: {{ finch.behavior}}</p>
      </div>
      <div class="card-action">
        <a href="{% url 'finch_update' finch.id %}">Edit</a>
        <a href="{% url 'finch_delete' finch.id %}">Delete</a>
      </div>
    </div>
  </div>
  <div class="col s6">
    <form action="{% url 'add_napping' finch.id %}" method="POST">
      {% csrf_token %} {{ napping_form.as_p }}
      <input type="submit" class="btn" value="Add Nap" />
    </form>
    <!-- new code above -->
    <table class="striped">
      <thead>
        <tr>
          <th>Date</th>
          <th>Nap Time</th>
        </tr>
      </thead>
      <tbody>
        {% for napping in finch.napping_set.all %}
        <tr>
          <td>{{napping.date}}</td>
          <td>{{napping.get_nap_display}}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
<hr>
<div class="row">
  <div class="col s6">
    <h3>{{ finch.name }}'s Seeds</h3>
    {% if finch.seeds.count %}
      {% for seed in finch.seeds.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
              A <span style="color: {{ seed.color }}">{{ seed.color }}</span> {{ seed.name }}
            </span>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>No Seeds 😔</h5>
    {% endif %}
  </div>
  <div class="col s6">
    <h3>Available Seeds</h3>
    {% if seeds.count %}
      {% for seed in seeds.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
              A <span style="color: {{ seed.color }}">{{ seed.color }}</span> {{ seed.name }}
            </span>
          </div>
          <div class="card-action">
            <form action="{% url 'assoc_seed' finch.id seed.id %}" method="POST">
              {% csrf_token %}
              <button type="submit" class="btn">Add</button>
            </form>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>{{finch.name}} Already Has All Seeds Available</h5>
    {% endif %}
  </div>
</div>

<script>
  const dateEl = document.getElementById("id_date")
  M.Datepicker.init(dateEl, {
    format: "yyyy-mm-dd",
    defaultDate: new Date(),
    setDefaultDate: true,
    autoClose: true,
  })
  const selectEl = document.getElementById("id_nap")
  M.FormSelect.init(selectEl)
</script>

{% endblock %}

main_app/templates/finches/index.html
{% extends 'base.html' %} 
{% block content %}

<h1>Finch List</h1>
{% for finch in finches %}
<div class="card">
  <a href="{% url 'detail' finch.id %}">
    <div class="card-content">
      <span class="card-title">{{ finch.name }}</span>
      <p>Size: {{ finch.size }}cm</p>
      <p>Color: {{ finch.color }}</p>
      <p>Behavior: {{ finch.behavior}}</p>
    </div>
  </a>
</div>

{% endfor %} 
{% endblock %}

main_app/templates/main_app/finch_confirm_delete.html
{% extends 'base.html' %} 
{% block content %}
<h1>Delete Finch</h1>

<h4>
  Are you sure you want to delete
  <span class="teal-text">{{ object.name }}</span>?
</h4>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes - Delete!" class="btn" />
  <a href="{% url 'detail' finch.id %}">Cancel</a>
</form>
{% endblock %}

main_app/templates/main_app/finch_form.html
{% extends 'base.html' %} 
{% block content %} 
{% if object %}
<h1>Edit <span class="teal-text">{{object.name}}</span></h1>
{% else %}
<h1>Add Finch</h1>
{% endif %}
<!-- Leaving the action empty makes the form post to the same url used to display it -->
<form action="" method="POST">
  <!-- Django requires the following for security purposes -->
  {% csrf_token %}
  <table>
    <!-- Render the inputs inside of <tr>s & <td>sss -->
    {{ form.as_table }}
  </table>
  <input type="submit" value="Update" class="btn" />
</form>
{% endblock %}

main_app/templates/main_app/seed_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Seed</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'seeds_detail' object.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/seed_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Seed Details</h1>

<div class="row">
  <div class="col s6 col-offset-3">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ seed.name }}</span>
        <p>Color: {{ seed.name }}</p>
      </div>
      <div class="card-action">
        <a href="{% url 'seeds_update' seed.id %}">Edit</a>
        <a href="{% url 'seeds_delete' seed.id %}">Delete</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

main_app/templates/main_app/seed_form.html
{% extends 'base.html' %}

{% block content %}
  {% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
  {% else %}
    <h1>Add Seed</h1>
  {% endif %}
  <!-- Leaving the action empty makes the form post to the same url used to display it -->
  <form action="" method="post">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}

main_app/templates/main_app/seed_list.html
{% extends 'base.html' %}
{% block content %}

Seed List
{% for seed in seed_list %}
<a href="{% url 'seeds_detail' seed.id %}">
    <div class="card">
        <div class="card-content">
            <span class="card-title">{{seed.name}}</span>
            <p>Color: {{seed.color}}</p>
        </div>
    </div>
</a>

{% endfor %}
{% endblock %}